### ISSUE TITLE
Не работает миграция через композитор в yii-basic-app-2.0.8

### ISSUE THREAD

**Issue by domeniktoredo** [CostaRico/yii2-images#48]
Не работает миграция через композитор в yii-basic-app-2.0.8

`C:\xampp\htdocs\first-e-shop.local\www>yii migrate/up --migrationPath=@vendor/costa-rico/yii2-images/migrations
Yii Migration Tool (based on Yii v2.0.9)

Creating migration history table "migration"...Done.
Total 2 new migrations to be applied:
        m140622_111540_create_image_table
        m140622_111545_add_name_to_image_table

Apply the above migrations? (yes|no) [no]:y
*** applying m140622_111540_create_image_table
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: m140622_111540_create_image_table::pk()'

in C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\base\Component.php:285

Stack trace:
#0 C:\xampp\htdocs\first-e-shop.local\www\vendor\costa-rico\yii2-images\migrations\m140622_111540_create_image_table.php(8): yii\base\Component->__call('pk', Array)
#1 C:\xampp\htdocs\first-e-shop.local\www\vendor\costa-rico\yii2-images\migrations\m140622_111540_create_image_table.php(8): m140622_111540_create_image_table->pk()
#2 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): m140622_111540_create_image_table->up()
#3 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m140622_111540_...')
#4 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#5 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#7 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
#8 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#9 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#10 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#11 C:\xampp\htdocs\first-e-shop.local\www\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#12 C:\xampp\htdocs\first-e-shop.local\www\yii(20): yii\base\Application->run()
#13 {main}

C:\xampp\htdocs\first-e-shop.local\www>`

Как сделать правильно?

**Comment by domeniktoredo** [comment]
Нашел решение https://github.com/CostaRico/yii2-images/pull/47/files
